import { z } from "zod";

export const wooProduct = z.object({
  id: z.number(),
  name: z.string(),
  slug: z.string(),
  permalink: z.string(),
  date_created: z.string(),
  date_modified: z.string(),
  type: z.string(),
  status: z.string(),
  featured: z.boolean(),
  catalog_visibility: z.string(),
  description: z.string(),
  short_description: z.string(),
  sku: z.string(),
  price: z.string(),
  regular_price: z.string(),
  sale_price: z.string(),
  date_on_sale_from: z.string().nullable(),
  date_on_sale_to: z.string().nullable(),
  price_html: z.string(),
  on_sale: z.boolean(),
  purchasable: z.boolean(),
  total_sales: z.number(),
  virtual: z.boolean(),
  downloadable: z.boolean(),
  downloads: z.array(z.unknown()),
  download_limit: z.number(),
  download_expiry: z.number(),
  external_url: z.string(),
  button_text: z.string(),
  tax_status: z.string(),
  tax_class: z.string(),
  manage_stock: z.boolean(),
  stock_quantity: z.number().nullable(),
  stock_status: z.string(),
  backorders: z.string(),
  backorders_allowed: z.boolean(),
  backordered: z.boolean(),
  sold_individually: z.boolean(),
  weight: z.string(),
  dimensions: z.unknown(),
  shipping_required: z.boolean(),
  shipping_taxable: z.boolean(),
  shipping_class: z.string(),
  shipping_class_id: z.number(),
  reviews_allowed: z.boolean(),
  average_rating: z.string(),
  rating_count: z.number(),
  related_ids: z.array(z.number()),
  upsell_ids: z.array(z.number()),
  cross_sell_ids: z.array(z.number()),
  parent_id: z.number(),
  purchase_note: z.string(),
  categories: z.array(z.unknown()),
  tags: z.array(z.unknown()),
  images: z.array(z.unknown()),
  attributes: z.array(z.unknown()),
  default_attributes: z.array(z.unknown()),
  variations: z.array(z.unknown()),
  grouped_products: z.array(z.unknown()),
  menu_order: z.number(),
  meta_data: z.array(z.object({
    id: z.number(),
    key: z.string(),
    value: z.any(),
  })),
  _links: z.unknown(),
});

export const mooCourse = z.object({
  id: z.number(),
  fullname: z.string(),
  displayname: z.string(),
  shortname: z.string(),
  courseimage: z.string().url(),
  categoryid: z.number(),
  categoryname: z.string(),
  sortorder: z.number(),
  summary: z.string(),
  summaryformat: z.number(),
  summaryfiles: z.array(z.any()), // Assuming it can be an array of any type
  overviewfiles: z.array(
    z.object({
      filename: z.string(),
      filepath: z.string(),
      filesize: z.number(),
      fileurl: z.string().url(),
      timemodified: z.number(),
      mimetype: z.string(),
    }),
  ),
  showactivitydates: z.boolean(),
  showcompletionconditions: z.boolean(),
  contacts: z.array(z.any()), // Assuming contacts can be an array of any type
  enrollmentmethods: z.array(z.string()),
});

export const wooOrder = z.object({
  id: z.number(),
  parent_id: z.number(),
  status: z.string(),
  currency: z.string(),
  version: z.string(),
  prices_include_tax: z.boolean(),
  discount_total: z.string(),
  discount_tax: z.string(),
  shipping_total: z.string(),
  shipping_tax: z.string(),
  cart_tax: z.string(),
  total: z.string(),
  total_tax: z.string(),
  customer_id: z.number(),
  order_key: z.string(),
  billing: z.object({
    first_name: z.string(),
    last_name: z.string(),
    company: z.string(),
    address_1: z.string(),
    address_2: z.string(),
    city: z.string(),
    state: z.string(),
    postcode: z.string(),
    country: z.string(),
    phone: z.string(),
    email: z.string(),
  }),
  shipping: z.object({
    first_name: z.string(),
    last_name: z.string(),
    company: z.string(),
    address_1: z.string(),
    address_2: z.string(),
    city: z.string(),
    state: z.string(),
    postcode: z.string(),
    country: z.string(),
    phone: z.string(),
  }),
  payment_method: z.string(),
  payment_method_title: z.string(),
  transaction_id: z.string(),
  customer_ip_address: z.string(),
  customer_user_agent: z.string(),
  created_via: z.string(),
  customer_note: z.string(),
  cart_hash: z.string(),
  number: z.string(),
  meta_data: z.array(
    z.object({
      id: z.number(),
      key: z.string(),
      value: z.any(),
    }),
  ),
  line_items: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
      product_id: z.number(),
      variation_id: z.number(),
      quantity: z.number(),
      tax_class: z.string(),
      subtotal: z.string(),
      subtotal_tax: z.string(),
      total: z.string(),
      total_tax: z.string(),
      taxes: z.array(z.any()),
      meta_data: z.array(z.any()),
      sku: z.string(),
      price: z.number(),
      image: z.object({
        id: z.string(),
        src: z.string(),
      }),
      parent_name: z.string().nullable(),
    }),
  ),
  tax_lines: z.array(z.any()),
  shipping_lines: z.array(z.any()),
  fee_lines: z.array(z.any()),
  coupon_lines: z.array(z.any()),
  refunds: z.array(z.any()),
  payment_url: z.string(),
  is_editable: z.boolean(),
  needs_payment: z.boolean(),
  needs_processing: z.boolean(),
  date_created: z.string(),
  date_created_gmt: z.string(),
  date_modified: z.string(),
  date_modified_gmt: z.string(),
  date_completed: z.string().nullable(),
  date_completed_gmt: z.string().nullable(),
  date_paid: z.string().nullable(),
  date_paid_gmt: z.string().nullable(),
  currency_symbol: z.string(),
  _links: z.object({
    self: z.array(
      z.object({
        href: z.string(),
        targetHints: z.any().optional(),
      }),
    ),
    collection: z.array(
      z.object({
        href: z.string(),
      }),
    ),
    customer: z.array(
      z.object({
        href: z.string(),
        targetHints: z.any().optional(),
      }),
    ),
  }),
});

export const wooProductCategory = z.object({
  id: z.number(),
  name: z.string(),
  slug: z.string(),
  parent: z.number(),
  description: z.string(),
  menu_order: z.number(),
  count: z.number(),
});

export const mooCourseModule = z.object({
  id: z.number(),
  name: z.string(),
  instance: z.number(),
  contextid: z.number(),
  description: z.string().optional(),
  visible: z.number(),
  uservisible: z.boolean(),
  visibleoncoursepage: z.number(),
  modicon: z.string().url(),
  modname: z.string(),
  purpose: z.string(),
  branded: z.boolean(),
  modplural: z.string(),
  availability: z.null(),
  indent: z.number(),
  onclick: z.string(),
  afterlink: z.null(),
  customdata: z.string(),
  noviewlink: z.boolean(),
  completion: z.number(),
  downloadcontent: z.number(),
  dates: z.array(z.unknown()),
  groupmode: z.number(),
  url: z.string().url().optional(),
});

export const mooCourseContent = z.object({
  id: z.number(),
  name: z.string(),
  visible: z.number(),
  summary: z.string(),
  summaryformat: z.number(),
  section: z.number(),
  hiddenbynumsections: z.number(),
  uservisible: z.boolean(),
  modules: z.array(mooCourseModule),
});
